### ISSUE TITLE
Blocage annotation

### ISSUE THREAD

**Issue by DamGLT** [PolytechLyon/isi3-tp-singleton-galochet_bouhana#1]
Bonjour,

C'est assez gênant mais nous ne parvenons tout simplement pas à faire la dernière partie du TP en utilisant les annotations.
Les informations que nous trouvons sur Internet, ou du moins ce que l'on parvient à en comprendre ne nous permettent pas de faire ce qui est attendu.
La manière dont on doit configurer l’application sans faire usage d'un fichier de configuration XML nous est plus que flou. Pouvez-vous nous aiguiller?

**Comment by Slashgear** [comment]
Qu'avez vous compris de l'usage des annotations pour Spring ? 

Cette config devrait vous débloquer
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd">

    <bean name="logger" class="logger.FileLogger" />

    <context:component-scan base-package="loggable" />

</beans>
```
