### ISSUE TITLE
Rendu TP

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-tp-singleton-galochet_bouhana#2]
TP non complet, vous partez avec un 0.

Certaines question (sur le static) n'étaient pas bloqué par votre question.

Je vous laisse un essai pour completer le rapport.

**Comment by DamGLT** [comment]
Bonjour,

Nos excuses, nous pensions avoir fini le TP.
Vous nous avez débloqué pour les annotations, et nous avons oublié de mettre à jour l'issue.

A vrai dire nous ne comprenons pas pourquoi le TP n'est pas complet.
